# Файлы Python
__pycache__/
*.pyc
*.pyo
*.pyd
.Python

# Файлы venv
.venv/

# Файлы IDE
.idea/
.vs/

# Docker
Dockerfile.web_app
Dockerfile.web_app.dockerignore
Dockerfile.max_bot
Dockerfile.max_bot.dockerignore
*.dockerignore
docker-compose.yml

# Git
.git
.gitignore

# Other
alembic/
alembic.ini
nginx/
web_app/
